name: ZchatOttotext
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
packages: {}
targets:
  ZchatOttotext:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: Sources
    resources:
      - path: Resources/ottoman_knowledge.txt
        type: file
      - path: Resources/osmanli2.txt
        type: file
      - path: Resources/ottoman.txt
        type: file
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: true
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.zchatottotext
        INFOPLIST_FILE: Info.plist
