name: ZchatOttotext
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
packages: {}
targets:
  ZchatOttotext:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: Sources
      - path: Sources/APIKey.swift
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: com.example.zchatottotext
        INFOPLIST_FILE: Info.plist
    resources:
      - path: Resources/ottoman.txt
      - path: Resources/Assets.xcassets
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: true
        UILaunchScreen: {}
